Repository nn-students-2021h2/Function_explorer_bot_8, pull requests merged in 2022-03, with the labels that each got.

#37 Code and patterns improvements
  .pylintrc
  requirements.txt
  resources/analysis_patterns.md
  source/conf/config.py
  source/core/bot.py
  source/math/analyse_patterns.json
  source/math/calculus_parser.py
  source/math/graph.py
  source/math/graph_parser.py
  source/math/math_function.py
  source/math/parser.py
Labels: bug, documentation, bot, analysis

#38 Asynchronous bot from aiogram with support for logging and anti-flood
  requirements.txt
  source/core/bot.py
  source/core/handling_msg.py
  source/extras/utilities.py
  source/math/calculus_parser.py
  source/math/graph.py
  source/math/graph_parser.py
  source/middleware/anti_flood_middleware.py
Labels: enhancement, bot, optimization

#40 Tests fixed
  requirements.txt
  tests/test_calculus_parser.py
  tests/test_graph_parser.py
  tests/test_math_function.py
Labels: bug

#42 Docker
  Dockerfile
  docker-compose.yml
  source/conf/default_config.json
Labels: enhancement

#43 Parsers use 'parse_expr' function instead of 'simplify'
  requirements.txt
  source/core/handling_msg.py
  source/math/analyse_patterns.json
  source/math/calculus_parser.py
  source/math/graph_parser.py
  source/math/math_function.py
  source/math/parser.py
  tests/test_calculus_parser.py
  tests/test_graph_parser.py
  tests/test_math_function.py
Labels: bug, drawing, analysis, optimization

#44 Russian and English localization
  .pylintrc
  locales/bot.pot
  locales/en/LC_MESSAGES/bot.mo
  locales/en/LC_MESSAGES/bot.po
  locales/ru/LC_MESSAGES/bot.mo
  locales/ru/LC_MESSAGES/bot.po
  source/core/bot.py
  source/core/handling_msg.py
  source/extras/translation.py
  source/math/calculus_parser.py
  source/math/graph.py
  source/math/graph_parser.py
  source/math/math_function.py
  source/math/parser.py
  source/middleware/anti_flood_middleware.py
  source/middleware/localization_middleware.py
  update_locales.sh
Labels: translations

#47 Adding and fixing buttons
  .pylintrc
  source/core/bot.py
Labels: bug, bot

#46 Add .dockerignore
  .dockerignore
Labels: docker

#48 Update README.md and CONTRIBUTING.md
  CONTRIBUTING.md
  README.md
Labels: documentation

#53 Dockerfile update
  Dockerfile
Labels: docker

#54 Async database and buttons
  .pylintrc
  locales/bot.pot
  locales/en/LC_MESSAGES/bot.mo
  locales/en/LC_MESSAGES/bot.po
  locales/ru/LC_MESSAGES/bot.mo
  locales/ru/LC_MESSAGES/bot.po
  requirements.txt
  resources/examples.json
  source/core/bot.py
  source/core/database.py
  source/core/handling_msg.py
  source/extras/utilities.py
  source/keyboards/inline_keyboards.py
  source/keyboards/reply_keyboards.py
  source/math/help_functions.py
  source/middleware/anti_flood_middleware.py
  source/middleware/localization_middleware.py
Labels: bot, database

#55 Add guides for graph and analysis
  locales/bot.pot
  locales/en/LC_MESSAGES/bot.mo
  locales/en/LC_MESSAGES/bot.po
  locales/ru/LC_MESSAGES/bot.mo
  locales/ru/LC_MESSAGES/bot.po
  source/core/handling_msg.py
  source/extras/translation.py
  source/math/help_functions.py
Labels: bot, translations

#56 Fix problem with looping of function_range / max / min Sympy functions
  resources/examples.json
  source/math/math_function.py
Labels: bug

#59 Readme update
  README.md
Labels: documentation

#60 Translation system Linux hot-fix
  source/core/bot.py
  source/extras/translation.py
Labels: bug

#61 Code corrections
  source/core/database.py
  source/core/handling_msg.py
Labels: enhancement, optimization

#62 Examples and axes intersection function fixes
  resources/examples.json
  source/math/math_function.py
Labels: bug
